config/routes.rb
York::Application.routes.draw do
  resources :maps

  resources :tweets

  root :to => 'tweets#index'

end

app/models/tweet.rb
class Tweet
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  validates_presence_of :screen_name, :location

  # location field format [latitude, longitude]
  # db.createCollection("tweets", {capped:true, size:100000, max:200000})
  # rake db:create_indexes or db.tweets.ensureIndex({location: "2d"})
  # db.tweets.find({location: {$near: [37.7863, -122.44]}}).limit(50)

  store_in "tweets", capped: true, size: 100000, max: 100000
  field :screen_name, type: String
  field :text, type: String
  field :location, type: Array  # [latitude, longitude]
  index [[:location, Mongo::GEO2D ]], min: -180, max: 180

  def as_json(options = {})
    { :screen_name => self.screen_name, 
      :text => self.text,
      :created_at => self.created_at.strftime("%m/%d %H:%M:%S"),
      :latitude => self.location[0], 
      :longitude => self.location[1] }
  end

  # create a tweet from line output of Twitter Stream API
  def self.create_from_stream(json)
    return if json['geo'].nil? || json['geo']['coordinates'].nil?
    tweet = Tweet.new(
      :created_at => Time.parse(json['created_at']),
      :screen_name => json['user']['screen_name'],
      :text => json['text'],
      :location => [json['geo']['coordinates'][0], json['geo']['coordinates'][1]]
    )
    if tweet.save
      Rails.logger.info "TWEET [#{tweet.location[0]},#{tweet.location[1]}] #{tweet.screen_name} - #{tweet.text}"
    else
      Rails.logger.error "Unable to save tweet: #{tweet.inspect}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  respond_to :html, :xml, :js
  def index
    if params[:lat]
      lat = params[:lat].to_f
      lon = params[:lon].to_f
      @tweets = Tweet.near(location: [lat, lon]).limit(50)
    else
      @tweets = Tweet.all.limit(100)
    end
    respond_with(@tweets)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json
  def index
    if params[:tweet]
      lat = params[:tweet]['lat'].to_f
      lon = params[:tweet]['lon'].to_f
      @tweets = Tweet.near(location: [lat, lon]).limit(50)
    else
      @tweets = Tweet.all.limit(50)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new
    @tweet = Tweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(params[:tweet])

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render json: @tweet, status: :created, location: @tweet }
      else
        format.html { render action: "new" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>York</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/maps/_form.html.erb
<%= form_for(@map) do |f| %>
  <% if @map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @map.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Editing map</h1>

<%= render 'form' %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<%= javascript_include_tag "jquery" %>
<%= javascript_include_tag "rails" %>
<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?sensor=false" %>
<%= javascript_include_tag "maps" %>

<script>
function initialize() {
  var mapOptions = {
    zoom: 10,
    center: new google.maps.LatLng(37.525, -122.155),
    mapTypeId: google.maps.MapTypeId.ROADMAP
  }
  cmMap = new google.maps.Map(document.getElementById("tweet_map"), mapOptions);
  cmMapData = <%= raw @tweets.to_json %>;
  cmLoadMap(cmMapData);

  google.maps.event.addListener(cmMap, 'idle', function() {
    if (this.isMapDragging) {
      this.idleSkipped = true;
      return;
    }
    this.idleSkipped = false;
    cmMapChanged();
  }.bind(this));
  google.maps.event.addListener(cmMap, 'dragstart', function() {
    this.isMapDragging = true;
  }.bind(this));
  google.maps.event.addListener(cmMap, 'dragend', function() {
    this.isMapDragging = false;
    if (this.idleSkipped == true) {
      cmMapChanged();
      this.idleSkipped = false;
    }
  }.bind(this));
  google.maps.event.addListener(cmMap, 'bounds_changed', function() {
    this.idleSkipped = false;
  }.bind(this));
}
</script>

<body onload="initialize()">
<div id="tweet_map" style="width: 800px; height: 600px;"></div>
</body>

app/views/maps/new.html.erb
<h1>New map</h1>

<%= render 'form' %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Tweets</h1>

<div id="content_menu">
  <%= form_for :tweet, :html => { :method => :get } do |f| %>
  <p>
    <label for="lat" class="map_menu">Latitude : </label>
    <%= f.text_field :lat, :value => params[:tweet] && params[:tweet]['lat'] %>
    <label for="lon" class="map_menu">Longitude : </label>
    <%= f.text_field :lon, :value => params[:tweet] && params[:tweet]['lon'] %>
  </p>
  <p>
    <%= f.submit "Show Tweets" %>
  </p>
  <% end %>
  <p>
    <h2> <%= link_to 'Show Map', maps_path %> </h1>
  </p>
</div>

<table>
  <tr>
    <th>TIME</th>
    <th>Location</th>
    <th>Screen Name</th>
    <th>Text</th>
  </tr>

<% @tweets.each do |tweet| %>
  <tr>
    <td><%= tweet.created_at.strftime("%m/%d %H:%M:%S") %>
    <td><%= "#{tweet.location[0]}, #{tweet.location[1]}" %>
    <td><%= tweet.screen_name %>
    <td><%= tweet.text %>
    <!-- <td><%= link_to 'Show', tweet %></td> -->
    <!-- <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td> -->
    <!-- <td><%= link_to 'Destroy', tweet, confirm: 'Are you sure?', method: :delete %></td> -->
  </tr>
<% end %>
</table>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>